____
Amazon Simple Email Service (Amazon SES) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails. It is a reliable, cost-effective service for businesses of all sizes that use email to keep in contact with their customers.
____

Add a dependency to AWS SES SDK:

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=awsses]
----

Create a service which encapsulates AWS credentials provider. The bean will not be loaded if the
system properties (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_KEY`) are not present.

[source,groovy]
.src/main/groovy/example/micronaut/AwsCredentialsProviderCondition.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/AwsCredentialsProviderCondition.groovy[]
----

[source,groovy]
.src/main/groovy/example/micronaut/AwsCredentialsProviderService.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/AwsCredentialsProviderService.groovy[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Bean will not loaded unless condition is met.
<3> Values will be resolved from system properties.

Create a service which sends the email with AWS Simple Email Service. The bean will not be loaded if the
system properties (`AWS_REGION`, `AWS_SOURCE_EMAIL`) are not present.

[source,groovy]
.src/main/groovy/example/micronaut/AwsSesMailCondition.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/AwsSesMailCondition.groovy[]
----

[source,groovy]
.src/main/groovy/example/micronaut/AwsSesMailService.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/AwsSesMailService.groovy[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Bean will not loaded unless condition is met.
<3> Bean will not loaded, if bean is not present.
<4> `@Primary` is a qualifier that indicates that a bean is the primary bean that should be selected in the case of multiple possible interface implementations.
<5> Values will be resolved from system properties.